baseURL = 'https://nicholas-lacourse93.github.io/'
languageCode = 'en-us'
title = 'Nicholas Lacourse'
theme='barks'
enableEmoji = true
Copyright = "Copyright &copy; 2022 Nicholas Lacourse. CC0 License."

[[menu.main]]
    name = "CV"
    weight = 50
    url = "https://nicholas-lacourse93.github.io/files/lacourse-nicholas-cv.pdf"

[params.head]
    author = "Nicholas Lacourse"
    # custom_css = "<url_to_custom_css_file>"
    description = "This is an academic webpage for Nicholas Lacourse"
    keywords = ["education", "science", "economics", "academic", "academia", "university"]

[params.colors]
    theme_color = "#333333"
    background_color = "#fcfbf9"
    text_color = "#333333"
    link_color = "#e74c3c"

[params.navigation]
    show_navigation = true

[params.footer]
    show_footer = true

[params.social]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:nicholas.lacourse@proton.me"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/nicholas-lacourse93"
        weight = 2
    # [params.social.google_scholar]
    #     name = "Google Scholar"
    #     class = "ai ai-google-scholar-square"
    #     url = ""
    #     weight = 3
    # [params.social.discord]
    #     name = "Discord"
    #     class = "fab fa-discord"
    #     url = ""
    #     weight = 4
    # [params.social.twitch]
    #     name = "Twitch"
    #     class = "fab fa-twitch"
    #     url = ""
    #     weight = 5
    [params.social.twitter]
        name = "Twitter"
        class = "fab fa-twitter"
        url = "https://twitter.com/nick_lacourse"
        weight = 6
    [params.social.instagram]
        name = "Instagram"
        class = "fab fa-instagram"
        url = "https://www.instagram.com/_nicholas_lacourse/"
        weight = 7
    # [params.social.patreon]
    #     name = "Patreon"
    #     class = "fab fa-patreon"
    #     url = ""
    #     weight = 8
    [params.social.kofi]
        name = "Ko-Fi"
        class = "fas fa-coffee"
        url = "https://ko-fi.com/nicholaslacourse"
        weight = 9
    # [params.social.youtube]
    #     name = "YouTube"
    #     class = "fab fa-youtube"
    #     url = ""
    #     weight = 10
    # [params.social.reddit]
    #     name = "Reddit"
    #     class = "fab fa-reddit"
    #     url = ""
    #     weight = 11
    [params.social.university]
        name = "My Institution"
        class = "fas fa-university"
        url = "https://business-school.exeter.ac.uk/about/departments/economics/"
        weight = 12
    # [params.social.linkedin]
    #     name = "LinkedIn"
    #     class = "fab fa-linkedin"
    #     url = ""
    #     weight = 13
    [params.social.orcid]
        name = "ORCID"
        class = "fab fa-orcid"
        url = "https://orcid.org/0000-0003-2092-7017"
        weight = 14
    # [params.social.spotify]
    #     name = "Spotify"
    #     class = "fab fa-spotify"
    #     url = ""
    #     weight = 15
