baseURL = 'https://nicholas-lacourse93.github.io/'
languageCode = 'en-us'
title = 'Nicholas Lacourse'
theme='barks'
enableEmoji = true

[params.head]
    author = "Nicholas Lacourse"
    # custom_css = "<url_to_custom_css_file>"
    description = "This is an academic webpage for Nicholas Lacourse"
    keywords = ["education", "science", "economics", "academic", "academia", "university"]
