baseURL = 'https://nicholaslacourse.com/'
languageCode = 'en-us'
title = 'Nicholas Lacourse'
theme = 'typo'

[params]
    theme = 'light'
    homeIntroContent = """
I am a recently graduated doctorate of economics from the University of Exeter.

I have broad knowledge across many fields of economics, but my academic work primarily rests within the belief formation literature. As of 2025, I am exploring how people update beliefs about themselves when they have to incur transaction costs to observe information, and how such a behavior varies across a wide range of characteristics.

Contact me: nicholaslacourse.official@gmail.com
"""

[[params.menu]]
name = "home"
url = "/"

# [[params.menu]]
# name = "posts"
# url = "/posts"

# [[params.menu]]
# name = "about"
# url = "/about"

[[params.menu]]
name = "research"
url = "/research"

[[params.menu]]
name = "teaching"
url = "/teaching"

[[params.menu]]
name = "resume"
url = "/files/personal_docs/resume.pdf"
newTab = true

[[params.social]]
name = "email"
url = "mailto:nicholaslacourse.official@gmail.com"

[[params.social]]
name = "github"
url = "https://github.com/nicholas-lacourse93"